# 03_mag_novel_species_summary.R ------------------------------------------
# Pipeline step 3 -- MAG classification
# Results section: 3.1 (unclassified fraction paragraph)
#
# Generates the manuscript-cited summary statistics for MAGs classified
# to genus but not species level (putatively novel species) in T0 Kefir4All
# samples. Specifically backs the following manuscript claims:
#
#   Water kefir T0 liquid:
#     - N participants with novel-species MAGs
#     - Genera recovered (Gluconobacter, Acetobacter, etc.)
#     - Completeness and contamination ranges
#     - Persistence across subsequent timepoints (T1-T6)
#
#   Milk kefir T0:
#     - Novel Lactobacillus sp. MAGs (n, ANI range)
#     - Statement that 36.3% unclassified fraction is NOT resolved by MAGs
#
# Input:
#   data/mag_metadata_v3.csv.gz   GTDB taxonomy + CheckM quality per MAG
#
# Outputs (written to resubmission/v2/supplmentary/ AND output/03_mag_classification/):
#   Supplementary_Table_S2_water_kefir_novel_species.tsv  — Supp Table S2 (water kefir)
#   Supplementary_Table_S2_milk_kefir_novel_species.tsv   — Supp Table S2 (milk kefir)
#   Supplementary_Table_S2_novel_species_persistence.tsv  — Supp Table S2 (persistence)
#
# Manuscript cross-reference:
#   Supplementary Table S1 — per-species RA values; generated by
#                             04_taxonomic_profiling/04_taxonomic_profiling.R
#   Supplementary Table S2 — novel-species MAG details; generated HERE

if (!requireNamespace("here",   quietly = TRUE)) install.packages("here")
if (!requireNamespace("pacman", quietly = TRUE)) install.packages("pacman")
library(here)
pacman::p_load(readr, dplyr, tidyr, stringr, ggplot2)

DATA_DIR <- here::here("data")
OUT_DIR  <- here::here("output", "03_mag_classification")
dir.create(OUT_DIR, recursive = TRUE, showWarnings = FALSE)
# NOTE: outputs below become Supplementary Table S2.
# After running, copy them manually to resubmission/v2/supplmentary/.

# -------------------------------------------------------------------------
# Load MAG metadata
# -------------------------------------------------------------------------
mag <- read_csv(file.path(DATA_DIR, "mag_metadata_v3.csv.gz"),
                show_col_types = FALSE)

# Deduplicate: mag_metadata_v3 carries one row per MAG per merge-join path;
# drop the second occurrence of any user_genome before any counting.
mag <- mag[!duplicated(mag$user_genome), ]

# Filter to Kefir4All samples only
mag_cs <- mag %>% filter(data_source == "This study")

# -------------------------------------------------------------------------
# Apply HQ filter: Completeness >= 50, Contamination <= 5
# -------------------------------------------------------------------------
mag_cs <- mag_cs %>%
  filter(as.numeric(Completeness) >= 50, as.numeric(Contamination) <= 5)

# -------------------------------------------------------------------------
# Identify novel-species MAGs
# Novel = GTDB-Tk could not assign species level:
#   note == "N/A" OR closest_placement_ani < 95
# -------------------------------------------------------------------------
mag_cs <- mag_cs %>%
  mutate(
    species      = gsub(".*;s__", "", classification),
    genus        = gsub(".*;g__|;s__.*", "", classification),
    is_novel_sp  = (note == "N/A" | as.numeric(closest_placement_ani) < 95),
    kefir_matrix = case_when(
      `kefir type` %in% c("WL", "WG") ~ "Water kefir",
      `kefir type` %in% c("ML", "MG") ~ "Milk kefir",
      TRUE ~ NA_character_
    ),
    sample_type  = case_when(
      `kefir type` %in% c("WL", "ML") ~ "liquid",
      `kefir type` %in% c("WG", "MG") ~ "grain",
      TRUE ~ NA_character_
    )
  )

# -------------------------------------------------------------------------
# WATER KEFIR T0 LIQUID — novel species summary
# -------------------------------------------------------------------------
wk_t0_liquid_novel <- mag_cs %>%
  filter(
    kefir_matrix == "Water kefir",
    sample_type  == "liquid",
    Stage        == "T0",
    is_novel_sp  == TRUE
  )

# Number of unique participants with novel-species MAGs
n_participants_wk <- wk_t0_liquid_novel %>%
  distinct(Sample) %>%
  nrow()
message("Water kefir T0 liquid — participants with novel-species MAGs: ",
        n_participants_wk)

# Genus-level breakdown: count MAGs, completeness and contamination ranges
wk_genus_summary <- wk_t0_liquid_novel %>%
  group_by(genus) %>%
  summarise(
    n_MAGs             = n(),
    mean_completeness  = round(mean(as.numeric(Completeness), na.rm = TRUE), 1),
    min_completeness   = round(min(as.numeric(Completeness),  na.rm = TRUE), 1),
    max_completeness   = round(max(as.numeric(Completeness),  na.rm = TRUE), 1),
    mean_contamination = round(mean(as.numeric(Contamination), na.rm = TRUE), 1),
    max_contamination  = round(max(as.numeric(Contamination),  na.rm = TRUE), 1),
    .groups = "drop"
  ) %>%
  arrange(desc(n_MAGs))

message("\nWater kefir T0 liquid — novel species by genus:")
print(wk_genus_summary)

# Overall completeness and contamination ranges across all novel WK MAGs
message("\nOverall completeness range (water kefir novel MAGs): ",
        min(as.numeric(wk_t0_liquid_novel$Completeness), na.rm = TRUE), " - ",
        max(as.numeric(wk_t0_liquid_novel$Completeness), na.rm = TRUE))
message("Overall contamination range: ",
        min(as.numeric(wk_t0_liquid_novel$Contamination), na.rm = TRUE), " - ",
        max(as.numeric(wk_t0_liquid_novel$Contamination), na.rm = TRUE))

# Supplementary Table S2 — water kefir novel species (genus-level summary)
s2_wk <- wk_genus_summary %>%
  mutate(kefir_type = "Water kefir", stage = "T0",
         sample_type = "liquid", n_participants = n_participants_wk)
write_tsv(s2_wk, file.path(OUT_DIR, "Supplementary_Table_S2_water_kefir_novel_species.tsv"))

# -------------------------------------------------------------------------
# WATER KEFIR PERSISTENCE — do these genera appear at later timepoints?
# -------------------------------------------------------------------------
novel_genera_wk <- unique(wk_t0_liquid_novel$genus)

wk_persistence <- mag_cs %>%
  filter(
    kefir_matrix == "Water kefir",
    genus        %in% novel_genera_wk,
    is_novel_sp  == TRUE
  ) %>%
  group_by(genus, Stage) %>%
  summarise(n_MAGs = n(), .groups = "drop") %>%
  arrange(genus, Stage)

message("\nWater kefir novel genera persistence across timepoints:")
print(as.data.frame(wk_persistence))

# Supplementary Table S2 — novel species persistence across timepoints
write_tsv(wk_persistence, file.path(OUT_DIR, "Supplementary_Table_S2_novel_species_persistence.tsv"))

# -------------------------------------------------------------------------
# WATER KEFIR T0 GRAIN — Acetobacter malorum + Saccharomycetaceae
# -------------------------------------------------------------------------
wk_t0_grain <- mag_cs %>%
  filter(kefir_matrix == "Water kefir", sample_type == "grain", Stage == "T0")

message("\nWater kefir T0 grain MAGs:")
print(wk_t0_grain %>% select(user_genome, genus, species, Completeness, Contamination))

# -------------------------------------------------------------------------
# MILK KEFIR T0 — novel species summary
# -------------------------------------------------------------------------
mk_t0_novel <- mag_cs %>%
  filter(
    kefir_matrix == "Milk kefir",
    Stage        == "T0",
    is_novel_sp  == TRUE
  )

message("\nMilk kefir T0 novel-species MAGs (all sample types):")
message("  Total: ", nrow(mk_t0_novel))

mk_novel_summary <- mk_t0_novel %>%
  group_by(genus, sample_type) %>%
  summarise(
    n_MAGs              = n(),
    mean_closest_ani    = round(mean(as.numeric(closest_placement_ani), na.rm = TRUE), 1),
    min_closest_ani     = round(min(as.numeric(closest_placement_ani),  na.rm = TRUE), 1),
    max_closest_ani     = round(max(as.numeric(closest_placement_ani),  na.rm = TRUE), 1),
    n_participants      = n_distinct(Sample),
    mean_completeness   = round(mean(as.numeric(Completeness), na.rm = TRUE), 1),
    .groups = "drop"
  )

message("\nMilk kefir T0 novel MAGs by genus and sample type:")
print(as.data.frame(mk_novel_summary))

# Supplementary Table S2 — milk kefir novel species
s2_mk <- mk_novel_summary %>% mutate(kefir_type = "Milk kefir", stage = "T0")
write_tsv(s2_mk, file.path(OUT_DIR, "Supplementary_Table_S2_milk_kefir_novel_species.tsv"))

# -------------------------------------------------------------------------
# MILK KEFIR T0 GRAIN — confirm only classified species recovered
# -------------------------------------------------------------------------
mk_t0_grain <- mag_cs %>%
  filter(kefir_matrix == "Milk kefir", sample_type == "grain", Stage == "T0")

message("\nMilk kefir T0 grain MAG species (should be only classified):")
print(sort(unique(mk_t0_grain$species)))

# -------------------------------------------------------------------------
# SUMMARY PRINT for manuscript verification
# -------------------------------------------------------------------------
message("\n========================================")
message("MANUSCRIPT NUMBERS VERIFICATION")
message("========================================")
message("Water kefir T0 liquid novel-species MAGs:")
message("  Participants: ", n_participants_wk)
message("  Genera: ", paste(sort(unique(wk_t0_liquid_novel$genus)), collapse = ", "))
message("  Completeness: ",
        round(min(as.numeric(wk_t0_liquid_novel$Completeness), na.rm = TRUE), 1),
        " - ",
        round(max(as.numeric(wk_t0_liquid_novel$Completeness), na.rm = TRUE), 1), "%")
message("  Max contamination: ",
        round(max(as.numeric(wk_t0_liquid_novel$Contamination), na.rm = TRUE), 1), "%")
message("")
message("Milk kefir T0 novel-species MAGs:")
message("  Total: ", nrow(mk_t0_novel))
message("  Genera: ", paste(sort(unique(mk_t0_novel$genus)), collapse = ", "))
message("  ANI to closest reference: ",
        round(min(as.numeric(mk_t0_novel$closest_placement_ani), na.rm = TRUE), 1),
        " - ",
        round(max(as.numeric(mk_t0_novel$closest_placement_ani), na.rm = TRUE), 1), "%")
message("  Milk kefir T0 grain species (classified only): ",
        paste(sort(unique(mk_t0_grain$species[mk_t0_grain$species != ""])), collapse = ", "))
message("========================================")
